#!/usr/bin/env bash
# working displays nums from 1 to 20
# addition to "bad luck from China" for the 4th iteration
# addition to "bad luck from Japan" for the 9th iteration
# addition to "bad luck from Italy" for the 17th loop iteration

counting=1

while [ $counting -le 20 ]
do
  echo "$counting"
  case $counting in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( counting++ ))
done